SELECT * FROM mybd.netflix;
select count(*) from mybd.netflix where type ='Movie';
select count(*) from mybd.netflix where type ='TV Show';
select show_id,title from mybd.netflix where show_id ='s1';
select type from mybd.netflix where title ='Blood & Water';
select title from mybd.netflix where country ='India';
select title from mybd.netflix where rating ='R';
select title from mybd.netflix where release_year ='2021';
select title from mybd.netflix where listed_in ='Documentaries';
select show_id, type, title, duration from mybd.netflix where type ='TV Show' and duration like '%season%';
select type, count(*) as total_count from mybd.netflix group by type order by total_count desc;
select rating, count(*) as total_title from mybd.netflix group by rating order by total_title desc;
Select title, type, release_year from mybd.netflix where release_year is not null order by release_year desc, title asc;
select show_id,title, listed_in from netflix where listed_in like '%Horror Movies%' and type ='Movie' order by title;
select type, count(*)as total_kids_content from netflix where listed_in like '%Kids%' group by type;
select title,release_year,listed_in from netflix where listed_in like '%Anime%' order by release_year;
select title,type,country from netflix where director is null or director = '' order by type;
select title,type from netflix where cast is null or cast = '' order by title;
select title, duration, release_year from netflix where title like '%Naruto%' order by release_year;
select title,duration,release_year from netflix	where title like '%Jaws%' order by release_year;
select country, count(*) as total_titles from netflix where country is not null or country = '' group by country order by total_titles desc limit 5;
select release_year, count(*) as total_titles from netflix group by release_year order by total_titles desc;
select listed_in, title from netflix where listed_in like '%Crime%' and type ='TV Show'order by title;
select title,duration from netflix where listed_in like '%Reality TV%' and type ='TV Show' order by duration desc;
select title,release_year,country from netflix where release_year <2000 order by release_year;
select title, type , country from netflix where date_added = 'September 24, 2021' order by title;
select count(*) as total_tittles from netflix where date_added like '%September%' and date_added is not null;
select type, title , rating from netflix where rating in('PG','TV-Y', 'TV-G') order by rating,title;
select title, country, type from netflix where country like '%United States%' order by type, title;
select title , release_year, duration from netflix where type = 'Movie' and rating = 'PG-13' and release_year > 2015 order by release_year desc;
select country, count(*) as country_title_total from netflix where country is not null group by country order by country_title_total desc;
select title, release_year from netflix where release_year = (select max(release_year) from netflix ) order by title;
select title , rating, case when rating ='TV-MA' then 'Mature' else 'General' end as 'category' from netflix order by category, title;
select title, release_year from netflix where release_year = ( select min(release_year) from netflix ) order by title;
select count(*) as drama_count from netflix where listed_in like '%Drama%' or listed_in like '%Dramas%';
select title, release_year from netflix where listed_in like '%Comedies%' order by release_year desc;
select title, type from netflix where country is null or country ='' order by title;
select type, title, cast, release_year from netflix where cast like '%Denzel Washington%' order by release_year;
select country, count(*) as total_tvshows from netflix where type ='TV Show' and country is not null group	by country order by total_tvshows desc limit 5;
select type, title, release_year from netflix where type = 'Movie' and release_year between 2015 and 2021 order by release_year desc;
select country, count(*) as total_titles from netflix where country is not null group by country order by total_titles desc;
select rating, count(*) as total_ratings from netflix where rating is not null group by rating order by total_ratings desc;
select listed_in, count(*) as total_titles from netflix group by listed_in order by total_titles desc;
select title, duration from netflix where type ='TV Show' and duration ='1 Season' order by title;
select title, director from netflix where director like '%,%' and type ='Movie' order by title;
select title,description from netflix where description like '%family%';
select title, release_year, case when release_year>=2015 then 'New' else 'Old' end as category from netflix order by release_year desc;
select release_year,type,  count(*) as total_titles from netflix group by release_year , type order by release_year desc;
select title ,cast from netflix where cast like '%Adam Sandler%' order by release_year;
select title, listed_in from netflix where listed_in like '%Dramas%' and listed_in like '%International Movie%' order by title ;



